### ISSUE TITLE
toolbar上面好像多了一条东西

### ISSUE THREAD

**Issue by Loren-Moon** [Othershe/NiceRead#2]
![screenshot_20160829-095256](https://cloud.githubusercontent.com/assets/12216747/18038772/a7515d12-6dce-11e6-8881-f12117c88de4.png)
![screenshot_20160829-095307](https://cloud.githubusercontent.com/assets/12216747/18038773/a7517aae-6dce-11e6-893f-71b3cc8278c2.png)

不知道是不是跟你布局把toolbar与tablayout拆开写的原因

**Comment by shehuan** [comment]
直接安装的apk吗？

**Comment by Loren-Moon** [comment]
不是，导入AS跑出来的

**Comment by shehuan** [comment]
这个问题之前有，在我目前的设置和模拟器上都修复了。是最新的代码？你的系统版本？或者你安装apk试试
