### ISSUE TITLE
我重写了你的代码，在GankDetailActivity中状态栏点击弹出的menu没有对齐，有什么解决办法吗？

### ISSUE THREAD

**Issue by mecury** [Othershe/NiceRead#3]

**Comment by shehuan** [comment]
没对齐是什么情况，这可以截个图吗

**Comment by mecury** [comment]
这是你的：
![Uploading S60831-101409.jpg…]()
我重写出来的：
![Uploading S60831-101340.jpg…]()

**Comment by mecury** [comment]
你的效果：
![1](https://cloud.githubusercontent.com/assets/12231723/18114261/666fc6da-6f68-11e6-909a-dcbc6a1369e1.jpg)
另一张上传不上去了，，，
就是这个图标显示比上图的大，字体也没有对齐

**Comment by shehuan** [comment]
你检查下图标的尺寸是否一致，或者更换下图标的目录。
