### ISSUE TITLE
onStart()的使用

### ISSUE THREAD

**Issue by Loren-Moon** [Othershe/NiceRead#4]
文档是这样描述的：onStart(): 这是 Subscriber 增加的方法。它会在 subscribe 刚开始，而事件还未发送之前被调用，可以用于做一些准备工作，例如数据的清零或重置。这是一个可选方法，默认情况下它的实现为空。需要注意的是，如果对准备工作的线程有要求（例如弹出一个显示进度的对话框，这必须在主线程执行）， onStart() 就不适用了，因为它总是**在 subscribe 所发生的线程被调用**，而不能指定线程。要在指定的线程来做准备工作，可以使用 doOnSubscribe() 方法。

Observable.create(onSubscribe)
    .subscribeOn(Schedulers.io())
    .doOnSubscribe(new Action0() {
        @Override
        public void call() {
            progressBar.setVisibility(View.VISIBLE); // 需要在主线程执行
        }
    })
    .subscribeOn(AndroidSchedulers.mainThread()) // 指定主线程
    .observeOn(AndroidSchedulers.mainThread())
    .subscribe(subscriber);

**Comment by shehuan** [comment]
虽然onStart()可能在子线程被调用，但我们有办法使里边的操作在UI线程执行，例如显示进度的对话框时，可以通过Handler切换到UI线程。当然使用doOnSubscribe()方法会更简单些。
